export const keysCases = {
    downCase: [' ','а', 'б', 'в', 'г', 'д', 'е', 'ё', 'ж', 'з', 'и', 'й', 'к', 'л', 'м', 'н', 'о', 'п', 'р', 'с', 'т', 'у', 'ф', 'х', 'ц', 'ч', 'ш', 'щ', 'ь', 'ы', 'ъ', 'э', 'ю', 'я', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', 'backspace'],
    upperCase: ['А', 'Б', 'В', 'Г', 'Д', 'Е', 'Ё', 'Ж', 'З', 'И', 'Й', 'К', 'Л', 'М', 'Н', 'О', 'П', 'Р', 'С', 'Т', 'У', 'Ф', 'Х', 'Ц', 'Ч', 'Ш', 'Щ', 'Ь', 'Ы', 'Ъ', 'Э', 'Ю', 'Я'],
    simbols: ['!', '@', '#', '$', '%', '&', '?', '-', '+', '=', '~'],
};

export const arrayList =[
    {setType: '5', content: 'Ё',  needShift: 'right', selected: false},
    {setType: '5', content: '1<sup>!</sup>', needShift: 'right', selected: false},
    {setType: '4', content: '2<sup>"</sup>', needShift: 'right', selected: false},
    {setType: '3', content: '3<sup>№</sup>', needShift: 'right', selected: false},
    {setType: '1.1', content: '4<sup>;</sup>', needShift: 'right', selected: false},
    {setType: '1.1', content: '5<sup>%</sup>', needShift: 'right', selected: false},
    {setType: '1', content: '6<sup>:</sup>',  needShift: 'left', selected: false},
    {setType: '1', content: '7<sup>?</sup>',  needShift: 'left', selected: false},
    {setType: '3', content: '8<sup>*</sup>',  needShift: 'left', selected: false},
    {setType: '4', content: '9<sup>(</sup>',  needShift: 'left', selected: false},
    {setType: '5', content: '0<sup>)</sup>',  needShift: 'left', selected: false},
    {setType: '5', content: '-<sup>_</sup>',  needShift: 'left', selected: false},
    {setType: '5', content: '=<sup>+</sup>',  needShift: 'left', selected: false},
    {setType: 'sys backspace', content: 'BACKSPACE', selected: false},

    {setType: 'sys tab', content: 'Tab'},
    {setType: '5', content: 'Й', needShift: 'right', selected: false},
    {setType: '4', content: 'Ц', needShift: 'right', selected: false},
    {setType: '3', content: 'У', needShift: 'right', selected: false},
    {setType: '1.1', content: 'К', needShift: 'right', selected: false},
    {setType: '1.1', content: 'Е', needShift: 'right', selected: false},
    {setType: '1', content: 'Н',  needShift: 'left', selected: false},
    {setType: '1', content: 'Г',  needShift: 'left', selected: false},
    {setType: '3', content: 'Ш',  needShift: 'left', selected: false},
    {setType: '4', content: 'Щ',  needShift: 'left', selected: false},
    {setType: '5', content: 'З',  needShift: 'left', selected: false},
    {setType: '5', content: 'Х',  needShift: 'left', selected: false},
    {setType: '5', content: 'Ъ',  needShift: 'left', selected: false},
    {setType: '5', content: '|<sup>/</sup>',  needShift: 'left', selected: false},

    {setType: 'sys caps', content: 'CapsLock'},
    {setType: '5', content: 'Ф', needShift: 'right', selected: false},
    {setType: '4', content: 'Ы', needShift: 'right', selected: false},
    {setType: '3', content: 'В', needShift: 'right', selected: false},
    {setType: '1.1', content: 'А', needShift: 'right', selected: false},
    {setType: '1.1', content: 'П', needShift: 'right', selected: false},
    {setType: '1', content: 'Р',  needShift: 'left', selected: false},
    {setType: '1', content: 'О',  needShift: 'left', selected: false},
    {setType: '3', content: 'Л',  needShift: 'left', selected: false},
    {setType: '4', content: 'Д',  needShift: 'left', selected: false},
    {setType: '5', content: 'Ж',  needShift: 'left', selected: false},
    {setType: '5', content: 'Э',  needShift: 'left', selected: false},
    {setType: 'sys enter', content: 'Enter', selected: false},

    {setType: 'sys shift', content: 'Shift', positionFor: 'left', selected: false},
    {setType: '5', content: 'Я', needShift: 'right', selected: false},
    {setType: '4', content: 'Ч', needShift: 'right', selected: false},
    {setType: '3', content: 'С', needShift: 'right', selected: false},
    {setType: '1.1', content: 'М', needShift: 'right', selected: false},
    {setType: '1.1', content: 'И', needShift: 'right', selected: false},
    {setType: '1', content: 'Т',  needShift: 'left', selected: false},
    {setType: '1', content: 'Ь',  needShift: 'left', selected: false},
    {setType: '3', content: 'Б',  needShift: 'left', selected: false},
    {setType: '4', content: 'Ю',  needShift: 'left', selected: false},
    {setType: '5', content: '.<sup>,</sup>', needShift: 'left'},
    {setType: 'sys shift', content: 'Shift', positionFor: 'right', selected: false},

    {setType: 'sys space', content: ' ', selected: false},    
]