import { keyboardCases, keyboardConfiguration } from "../types/keyboardConfiguration";

export const keysCases: keyboardCases = {
    downCase: [' ','а', 'б', 'в', 'г', 'д', 'е', 'ё', 'ж', 'з', 'и', 'й', 'к', 'л', 'м', 'н', 'о', 'п', 'р', 'с', 'т', 'у', 'ф', 'х', 'ц', 'ч', 'ш', 'щ', 'ь', 'ы', 'ъ', 'э', 'ю', 'я', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', 'Backspace'],
    upperCase: ['А', 'Б', 'В', 'Г', 'Д', 'Е', 'Ё', 'Ж', 'З', 'И', 'Й', 'К', 'Л', 'М', 'Н', 'О', 'П', 'Р', 'С', 'Т', 'У', 'Ф', 'Х', 'Ц', 'Ч', 'Ш', 'Щ', 'Ь', 'Ы', 'Ъ', 'Э', 'Ю', 'Я'],
    symbols: ['!', '@', '#', '$', '%', '&', '?', '-', '+', '=', '~'],
};

export const arrayList: Array<keyboardConfiguration> = [
    {setType: '5', content1: 'Ё',   needShift: 'right', selected: false},
    {setType: '5', content1: '1', content2:'!', needShift: 'right', selected: false},
    {setType: '4', content1: '2', content2: '"', needShift: 'right', selected: false},
    {setType: '3', content1: '3', content2: '№',needShift: 'right', selected: false},
    {setType: '1.1', content1: '4', content2: ';', needShift: 'right', selected: false},
    {setType: '1.1', content1: '5', content2: '%', needShift: 'right', selected: false},
    {setType: '1', content1: '6', content2: ':',  needShift: 'left', selected: false},
    {setType: '1', content1: '7', content2: '?',  needShift: 'left', selected: false},
    {setType: '3', content1: '8', content2: '*',  needShift: 'left', selected: false},
    {setType: '4', content1: '9', content2: '(',  needShift: 'left', selected: false},
    {setType: '5', content1: '0', content2: ')',  needShift: 'left', selected: false},
    {setType: '5', content1: '-', content2: '_',  needShift: 'left', selected: false},
    {setType: '5', content1: '=', content2: '+',  needShift: 'left', selected: false},
    {setType: 'sys backspace', content1: 'Backspace', selected: false},

    {setType: 'sys tab', content1: 'Tab',  selected: false},
    {setType: '5', content1: 'Й',  needShift: 'right', selected: false},
    {setType: '4', content1: 'Ц',  needShift: 'right', selected: false},
    {setType: '3', content1: 'У',  needShift: 'right', selected: false},
    {setType: '1.1', content1: 'К',  needShift: 'right', selected: false},
    {setType: '1.1', content1: 'Е', needShift: 'right', selected: false},
    {setType: '1', content1: 'Н',   needShift: 'left', selected: false},
    {setType: '1', content1: 'Г',  needShift: 'left', selected: false},
    {setType: '3', content1: 'Ш',   needShift: 'left', selected: false},
    {setType: '4', content1: 'Щ',   needShift: 'left', selected: false},
    {setType: '5', content1: 'З',   needShift: 'left', selected: false},
    {setType: '5', content1: 'Х',   needShift: 'left', selected: false},
    {setType: '5', content1: 'Ъ',   needShift: 'left', selected: false},
    {setType: '5', content1: '|',  content2: '/', needShift: 'left', selected: false},

    {setType: 'sys caps', content1: 'CapsLock', selected: false},
    {setType: '5', content1: 'Ф', needShift: 'right', selected: false},
    {setType: '4', content1: 'Ы',  needShift: 'right', selected: false},
    {setType: '3', content1: 'В',  needShift: 'right', selected: false},
    {setType: '1.1', content1: 'А', needShift: 'right', selected: false},
    {setType: '1.1', content1: 'П', needShift: 'right', selected: false},
    {setType: '1', content1: 'Р',   needShift: 'left', selected: false},
    {setType: '1', content1: 'О',   needShift: 'left', selected: false},
    {setType: '3', content1: 'Л',   needShift: 'left', selected: false},
    {setType: '4', content1: 'Д',   needShift: 'left', selected: false},
    {setType: '5', content1: 'Ж',   needShift: 'left', selected: false},
    {setType: '5', content1: 'Э',   needShift: 'left', selected: false},
    {setType: 'sys enter', content1: 'Enter',  selected: false},

    {setType: 'sys shift', content1: 'Shift',  positionFor: 'left', selected: false},
    {setType: '5', content1: 'Я',  needShift: 'right', selected: false},
    {setType: '4', content1: 'Ч',  needShift: 'right', selected: false},
    {setType: '3', content1: 'С',  needShift: 'right', selected: false},
    {setType: '1.1', content1: 'М',  needShift: 'right', selected: false},
    {setType: '1.1', content1: 'И',  needShift: 'right', selected: false},
    {setType: '1', content1: 'Т',   needShift: 'left', selected: false},
    {setType: '1', content1: 'Ь',   needShift: 'left', selected: false},
    {setType: '3', content1: 'Б',   needShift: 'left', selected: false},
    {setType: '4', content1: 'Ю',   needShift: 'left', selected: false},
    {setType: '5', content1: '.', content2: ',', needShift: 'left', selected: false},
    {setType: 'sys shift', content1: 'Shift', positionFor: 'right', selected: false},

    {setType: 'sys space', content1: ' ',  selected: false, needShift: undefined},    
]